// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIfSXN8lcCBINt1WhhfVnsSkWf5ubOg00',
    appId: '1:297611912188:web:7b12cee52ca02ca9d64879',
    messagingSenderId: '297611912188',
    projectId: 'petking-e9d2b',
    authDomain: 'petking-e9d2b.firebaseapp.com',
    storageBucket: 'petking-e9d2b.appspot.com',
    measurementId: 'G-S6FPD818N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuV0qcaSA65ECUe1JIvdbRG4a8xKbdx6Q',
    appId: '1:297611912188:android:12c2e5b91314680ad64879',
    messagingSenderId: '297611912188',
    projectId: 'petking-e9d2b',
    storageBucket: 'petking-e9d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHicAK6FHyRWbBY66c45_hmnNBRGcnFo',
    appId: '1:297611912188:ios:c1f6a2b4efceff79d64879',
    messagingSenderId: '297611912188',
    projectId: 'petking-e9d2b',
    storageBucket: 'petking-e9d2b.appspot.com',
    iosClientId: '297611912188-cl8ouncbpabj8bikeka9fpb9lmn4fr8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.petking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHicAK6FHyRWbBY66c45_hmnNBRGcnFo',
    appId: '1:297611912188:ios:8633909f6a12d638d64879',
    messagingSenderId: '297611912188',
    projectId: 'petking-e9d2b',
    storageBucket: 'petking-e9d2b.appspot.com',
    iosClientId: '297611912188-rk6h8k0hntnjj9peb1tvidavfgva7vr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.petking.RunnerTests',
  );
}
